#------------------------------------------------------------------------------
#  Copyright (c) 2012, Enthought, Inc.
#  All rights reserved.
#------------------------------------------------------------------------------
from .declarative import Declarative
from .enaml_def import EnamlDef


def _make_enamldef_helper_(name, base, builder):
    """ A compiler helper function for creating a new EnamlDef type.

    This function is called by the bytecode generated by the Enaml
    compiler when an enaml module is imported. It is used to make new
    types from the 'enamldef' keyword.

    This helper will raise an exception if the base type is of an
    incompatible type.

    Parameters
    ----------
    name : str
        The name to use when generating the new type.

    base : type
        The base class to use for the new type. This must be a subclass
        of Declarative.

    builder : FunctionType
        The builder function created by the Enaml compiler. This
        function will be used during instantiation to populate new
        instances with children and expressions.

    Returns
    -------
    result : EnamlDef
        A new enamldef subclass of the given base class.

    """
    dct = {'__module__': builder.__module__, '__doc__': builder.__doc__}
    if not isinstance(base, type) or not issubclass(base, Declarative):
        msg = "can't derive enamldef from '%s'"
        raise TypeError(msg % base)
    decl_cls = EnamlDef(name, (base,), dct)
    decl_cls._builders = base._builders + (builder,)
    return decl_cls

