<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tml</string>
	</array>
	<key>name</key>
	<string>TraitsML</string>
	<key>patterns</key>
	<array>
        <dict>
            <key>comment</key>
            <string>TraitsML element name and optional identifier</string>
            <key>match</key>
            <string>^\s*([A-Za-z_][A-Za-z0-9_]*)\s*(?:([A-Za-z_][A-Za-z0-9_]*)*)\s*:\s*$</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.class</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag</string>
                </dict>
            </dict>
        </dict>
		<dict>
			<key>comment</key>
			<string>TraitsML meta info names and optional identifiers</string>
			<key>match</key>
			<string>^\s*(@)\s*([A-Za-z_][A-Za-z0-9_]*)\s*(?:([A-Za-z_][A-Za-z0-9_]*)*)\s*:\s*$</string>
			<key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.decorator</string>
                </dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.decorator</string>
				</dict>
                <key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>comment</key>
			<string>TraitsML property expressions</string>
			<key>begin</key>
			<string>^\s*([A-Za-z_][A-Za-z_0-9]*)\s*(=|:=|&lt;&lt;|&gt;&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
        <dict>
			<key>comment</key>
			<string>TraitsML comment</string>
			<key>match</key>
			<string>^\s*(#.*)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
			</dict>
		</dict>
        <dict>
            <key>match</key>
			<string>\b(?:(import)|(from))\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.python</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.from.python</string>
				</dict>
			</dict>
		</dict>	
	</array>
	<key>scopeName</key>
	<string>source.python.traitsml</string>
	<key>uuid</key>
	<string>42F00A35-6D17-44B8-8C9B-438F9FE9E241</string>
</dict>
</plist>
